version: '3'
services:
  predis:
    hostname: predis
    image: redis:latest
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3.10-management
    command: "rabbitmq-server"
    environment:
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_VHOST=pla
    ports:
      - "5672:5672"
      - "15672:15672"
  charge:
    build:
      context: .
      dockerfile: charge_service/Dockerfile
    container_name: charge
    restart: always
    # tty: true
    # stdin_open: true
    # command: cat
    command: python main.py
    ports:
      - 5761:5002
    env_file:
      - charge_service/.env
    volumes:
      - ./charge_service:/app
      - ./common:/app/common

  charge-db:
    container_name: charge-db
    image: mongo
    ports:
      - "27017"
    volumes:
      - data:/bitnami/mongodb

  dispatcher:
    build:
      context: .
      dockerfile: dispatcher/Dockerfile
    container_name: dispatcher
    restart: always
    command: python app.py
    ports:
      - 6163:5001
    env_file:
      - dispatcher/.env
    volumes:
      - ./dispatcher:/app
      - ./common:/app/common
  customer:
    build:
      context: .
      dockerfile: customer_service/Dockerfile
    container_name: customer
    restart: always
    command: python main.py
    ports:
      - 8080:8080
    env_file:
      - customer_service/.env
    volumes:
      - ./customer_service:/app
      - ./common:/app/common
  master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./tests:/mnt/locust
    command: -f /mnt/locust/loadtest.py --master

  worker:
    image: locustio/locust
    volumes:
      - ./tests:/mnt/locust
    command: -f /mnt/locust/loadtest.py --worker --master-host master
volumes:
  data:
